version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mydb
    restart: always
    ports:
      - "5344:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sag_network
  

  redis:
    image: redis:6.2
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: myredis
    restart: always
    ports:
      - "7008:6379"
    volumes:
      - redis_data:/data
    networks:
      - sag_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - sag_network
      
volumes:
  postgres-data:
  redis_data:
networks:
  sag_network:
    driver: bridge  