version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mydb
    restart: always
    ports:
      - "5344:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
      
volumes:
  postgres-data: