export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
export const POLICLINICAS_REPOSITORY = 'POLICLINICAS_REPOSITORY';
export const PACIENTES_REPOSITORY = 'PACIENTES_REPOSITORY';
export const UBS_REPOSITORY = 'UBS_REPOSITORY';

export const POLICLINICAS_SERVICE = 'POLICLINICAS_SERVICE';
export const PACIENTES_SERVICE = 'PACIENTES_SERVICE';
export const USUARIOS_SERVICE = 'USUARIOS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const UBS_SERVICE = 'UBS_SERVICE';